#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
# Configure Nginx server so that /redirect_me is redirecting to another page
# Redirection must be a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 30
sudo service nginx restart
