#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config="
frontend  nathan-frontend
        bind *:80
        mode http
        default_backend nathan-backend 
        timeout client 30s

backend nathan-backend
        mode http
        balance roundrobin
        timeout connect 5s
        timeout server 30s
        server 03-web-01 35.175.126.214:80 check
        server 03-web-02 3.84.238.153:80 check
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg >/dev/null

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee /etc/default/haproxy >/dev/null

sudo service haproxy restart
